string name
geometry_msgs/Pose pose
bool add_close_nodes       # Set to true to connect to nodes which are in close proximity (currently hardcoded to 8m)
bool add_previous_node     # connecting this node to previously added node
string previous_node_name  # specify node to connect to (if add_previous_node) else connect to previously added node
string action              # action of edges connecting this node to close nodes and previous added node (default move_base)
string action_type         # action type of edges connecting this node to close nodes and previous added node (default move_base_msgs/MoveBaseGoal)
bool one_way               # one way connection from previous node to this node if `add_previous_node` else bi-directional
---
bool success
string message             # node name
