string edge_id
string name           # name of inserted node
float32 x             # Optional x position of inserted node. Default=0.0 meters (mean of origin and destination)
float32 y             # Optional y position of inserted node. Default=0.0 meters (mean of origin and destination)
---
bool success
string message
